# Promises

The Promise object represents the eventual completion (or failure) of an asynchronous operation and its resulting value.
Promise is an object that may produce a value in future. This value will be a value that is resolved or a reason why its rejected or not resolved. A promise is a placeholder for a value that we don't have now but will have later; it's a guarantee that we will know the results of an asynchronous computation. Promises are great JavaScript addition that helps to avoid the hellish callback issue.

- usefull when dealing with asynchronous code
- making server calls, etc
- don't block website or applications
- promise executes callbacks on success or failure
- can have another callback always executed
- promise states: pending, resolved, rejected
- you can chain multiple promises

Promise can be in one of the 3 possible states:

- **Pending:** initial state, neither fulfilled nor rejected. Initial State, before the Promise succeeds or fails
- **Fulfilled:** â€“ Resolved: operation completed successfully
- **Rejected:** failed promise

To create a promise, we use the new, built-in **Promise** constructor, to which we pass a function, which is called an executor function, and has two parameters:

- **resolve** - a success callback
- **reject** - a failure callback

```js
Promise.resolve("Success")
  .then((res) => console.log(res))
  // catch will never execute with Promise.resolve
  .catch((e) => console.log(e));

Promise.reject(new Error("Failed"))
  // then() will never execute with Promise.reject
  .then((res) => console.log(res))
  .catch((e) => console.log(e));
```

## Chaining Promises

```js
new Promise(function (resolve, reject) {
  setTimeout(() => resolve(1), 1000);
})
  .then(function (result) {
    return result + 2;
  })
  .then(function (result) {
    return result + 2;
  })
  .then(function (result) {
    return result + 2;
  })
  .catch((error) => console.log(error));
```

## Handling multiple Promises

```js
const promiseOne = new Promise((resolve, reject) => {
  setTimeout(resolve, 2500, "promise one");
});

const promiseTwo = new Promise((resolve, reject) => {
  setTimeout(resolve, 3500, "promise two");
});

const promiseThree = new Promise((resolve, reject) => {
  setTimeout(resolve, 1500, "promise three");
});

Promise.race([promiseOne, promiseTwo, promiseThree])
  .then((data) => console.log(data))
  .catch((e) => console.log(e));

Promise.all([promiseOne, promiseTwo, promiseThree])
  .then((data) => console.log(data))
  .catch((e) => console.log(e));

Promise.allSettled([promiseOne, promiseTwo, promiseThree])
  .then((data) => console.log(data))
  .catch((e) => console.log(e));
```

## AJAX calls with **_fetch_** and Promise

1. **_fetch_** will return a promise.
2. Consume the Promise with **_then_** & **_catch_**.

```js
fetch("https://jsonplaceholder.typicode.com/users")
  .then((result) => {
    console.log(result);
    return result.json();
  })
  .then((data) => {
    console.log(data);
    return data;
  })
  .catch((err) => {
    console.log(err);
  });
```

1. **_fetch_** will return a promise.
2. Consume the Promise with **_async_** & **_await_**.

```js
try {
  const response = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await response.json();
  console.log(data);
} catch (err) {
  console.error(err);
}
```

## Promises with **async** and **await**

```js
async function foo() {
  const promise = new Promise((resolve, reject) => {
    setTimeout(resolve, 2500, "promise");
  });

  const result = await promise;
}
```

## Promises with **_for_**...**_await_**

```js
const urls = [
  "https://jsonplaceholder.typicode.com/posts",
  "https://jsonplaceholder.typicode.com/comments",
  "https://jsonplaceholder.typicode.com/photos",
  "https://jsonplaceholder.typicode.com/todos",
];

const getData = async () => {
  const pendingPromises = urls.map((url) => fetch(url));

  for await (const promise of pendingPromises) {
    const data = await promise.json();
    console.log(data);
  }
};

getData();
```

---

```js
function successHandler(result) {
  console.log("I think my promise resolved, success!", result);
}
function failureHandler(error) {
  console.log("I think my promise rejected, failure!", error);
}
function finallyHandler() {
  console.log("success or failure, I always execute!");
}
const myPromise = new Promise(function (resolve, reject) {
  const randomNumber = (Math.random() * 100).toFixed(0);

  if (randomNumber % 2 === 0) {
    resolve("Number IS divisible by 2: " + randomNumber);
  } else {
    reject("Number NOT divisible by 2: " + randomNumber);
  }
});
myPromise.then(successHandler).catch(failureHandler).finally(finallyHandler);
```

```js
function getUserData(url) {
  return new Promise(function (resolve, reject) {
    if (url.indexOf("http") === 0) {
      resolve("data retrieved");
    } else {
      reject("something went wrong");
    }
  });
}

function loginUser(userUrl) {
  getUserData(userUrl)
    .then(function (data) {
      console.log(data);
    })
    .catch(function (error) {
      console.log(error);
    });
}
loginUser("http://www.fakesite.com?user=bsmith");
loginUser("htp://www.fakesite.com?user=bsmith");
```
